# Generated by Django 3.2 on 2021-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='on_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='На главную'),
        ),
    ]
